spring.datasource.url: jdbc:h2:file:./camunda-h2-database

logging:
  level:
    org:
      springframework:
        security: DEBUG



spring:
  datasource:
#    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/camunda
    username: camunda
    password: camunda

camunda.bpm.admin-user:
  id: camunda
  password: password